"""add unique constraint to subscriptions

Revision ID: 29d3b2b5b7fa
Revises: ea14eb5fe6d2
Create Date: 2026-10-06 16:11:11.002321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d3b2b5b7fa'
down_revision: Union[str, Sequence[str], None] = 'ea14eb5fe6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_subscriptions_target_url'), 'subscriptions', ['target_url', 'event_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_subscriptions_target_url'), 'subscriptions', type_='unique')
    # ### end Alembic commands ###
